### ISSUE TITLE
In mobile Safari the user must precisely tap the input field to bring up the keyboard

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/parchment#27]
[Zarf wrote:](http://inform7.com/mantis/view.php?id=1879#c4391)

> (It has other problems -- you have to tap on the invisible input field to bring up the keyboard, which can be a nuisance. I can make the menus work though.)

**Comment by cibersheep** [comment]
Hi!
It happens something similar in the web browser of Ubuntu Touch. After pressing enter, message is printed, last command updated and cursor don't go to the input field (that's why on screen keyboard goes away). With a external keyboard, cursor is not visible until typing something (no letter are missing)

**Comment by dfabulich** [comment]
I think https://github.com/erkyrath/glkote/pull/51 and https://github.com/erkyrath/glkote/pull/58 will fix this.
