### ISSUE TITLE
trying to create mobile app

### ISSUE THREAD

**Issue by deacege** [curiousdannii/parchment#28]
first sorry for my bad english, I'm creating a mobile app using parchment and phonegap, I can save for each game and store it in a file, etc. the app could say that is working, except for open local files, it only works when you download from other sites, I need to open the files using the "fileOpen" plugin of phonegap, but would not know very well where in the code add this
could you just tell me where in the code opens a file?
so I could change it and keep trying

this is my mail if you prefer: deacege[at]outlook.com

**Comment by curiousdannii** [comment]
Are you able to open the files and then resave them locally to the same place as where the index.html is? Sometimes local files can't be opened in browsers, but if it's in the same folder it should be fine.

Alternatively you would need to convert it to a JS file (using the same process as the zcode.appspot.com does) and save that locally. Browsers can always load JS files, so that is the safe backup option.
