### ISSUE TITLE
Difference between using a .z file and a .z.js file

### ISSUE THREAD

**Issue by nickbe** [curiousdannii/parchment#35]
It seems I can use the zcode files as well as the .js files. Can you explain the difference?

Also I'd like to know how to convert the zcode files to .js myself. There seem to be some tools in a subfolder but so far I couldn't figure out how to use them,

And if I use story files with in game sound or graphics - will they work too?

**Comment by curiousdannii** [comment]
The .js story files are just base64 encoded copies of the original files, with a header and tail so that they can be loaded. They are only needed when loading a story from file: and possibly only from old browsers. I haven't checked for a while, but it may not be needed at all now!

Graphics are supported by Quixe (the Glulx interpreter Parchment uses). I'm not sure if it supports sound or not. See https://github.com/erkyrath/quixe/issues/5

**Comment by nickbe** [comment]
Thanks for the info :)

**Comment by cibersheep** [comment]
Actually, in the Ubuntu Phone, the easiest way of doing an IF app is embeding an html with Parchment. The compiler complains about having "bin files .z5" so being able to have the .z5.js has been really helpful.

Just saying :)
Anyway, if it's depreciated, I will cry a bit and that's it :)
